<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE ProvisioningTransaction PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<ProvisioningTransaction accountDisplayName="CN=Claire.Divas,OU=Test,DC=ENH,DC=local" applicationName="Active Directory" integration="Active Directory" name="0000000001" nativeIdentity="CN=Claire.Divas,OU=Test,DC=ENH,DC=local" operation="Create" source="LCM" status="Failed" type="Auto">
  <Attributes>
    <Map>
      <entry key="request">
        <value>
          <AccountRequest application="Active Directory" nativeIdentity="CN=Claire.Divas,OU=Test,DC=ENH,DC=local" op="Create" targetIntegration="Active Directory">
            <Attributes>
              <Map>
                <entry key="provisioningTransactionId" value="0a00030f8d871ee9818d87ffdf2c000f"/>
              </Map>
            </Attributes>
            <AttributeRequest name="cn" op="Set" value="Claire.Divas"/>
            <AttributeRequest name="distinguishedName" op="Set" value="CN=Claire.Divas,OU=Test,DC=ENH,DC=local"/>
            <AttributeRequest name="givenName" op="Set" value="Claire"/>
            <AttributeRequest name="sn" op="Set" value="Divas"/>
            <AttributeRequest name="objectType" op="Set" value="User"/>
            <AttributeRequest name="sAMAccountName" op="Set" value="Claire.Divas"/>
            <AttributeRequest name="password" op="Set">
              <Attributes>
                <Map>
                  <entry key="secret" value="true"/>
                </Map>
              </Attributes>
            </AttributeRequest>
            <AttributeRequest name="IIQDisabled" op="Set">
              <Value>
                <Boolean/>
              </Value>
            </AttributeRequest>
            <AttributeRequest name="msNPAllowDialin" op="Set" value="Not Set"/>
            <ProvisioningResult status="failed">
              <Errors>
                <Message key="Exception occurred while executing the RPCRequest: Errors returned from IQService. &quot;The object already exists. 00000524: UpdErr: DSID-031A11C4, problem 6005 (ENTRY_EXISTS), data 0 . HRESULT:[0x80071392] For identity: CN=Claire.Divas,OU=Test,DC=ENH,DC=local&quot;" type="Error"/>
              </Errors>
            </ProvisioningResult>
          </AccountRequest>
        </value>
      </entry>
    </Map>
  </Attributes>
</ProvisioningTransaction>